version: "3.6"
services:
  # Master
  master-node:
    image: "binhvd/spark-cluster:0.16"
    command: bash -c "/home/big_data/jupyter.sh; /home/big_data/spark-cmd.sh start master-node;"
    hostname: master-node
    networks:
      - cluster-net
    volumes:
      # - "./data:/home/big_data/data" # Your data
      - hdfs-master-index:/home/hadoop/data/nameNode
      - hdfs-master-checkpoint:/home/hadoop/data/namesecondary
      - hdfs-master-data:/home/hadoop/data/dataNode
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==manager

  # Workers
  worker:
    image: "binhvd/spark-cluster:0.16"
    command: bash -c "/home/big_data/spark-cmd.sh start"
    networks:
      - cluster-net
    volumes:
      - hdfs-worker-data:/home/hadoop/data/dataNode
    depends_on:
      - "master-node"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role!=manager

volumes:
  hdfs-master-index:
    name: 'hdfs_master_index'
  hdfs-master-checkpoint:
    name: 'hdfs_master_checkpoint'
  hdfs-master-data:
    name: 'hdfs_master_data'
  hdfs-worker-data:
    name: 'hdfs_worker_data'

# Uses host network
networks:
  cluster-net:
    name: host
    external: true
    driver_opts:
      com.docker.network.driver.mtu: 1280
