version: "3.6"
services:
  # Master
  master-node:
    image: "binhvd/spark-cluster:0.10"
    command: bash -c "/home/big_data/jupyter.sh; /home/big_data/spark-cmd.sh start master-node;"
    hostname: master-node
    networks:
      - cluster-net
    ports:
      - 8088:8088
      - 8080:8080
      - 9870:9870
      - 18080:18080
      - 8888:8888
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role==manager

  # Workers
  worker:
    image: "binhvd/spark-cluster:0.10"
    command: bash -c "/home/big_data/spark-cmd.sh start"
    networks:
      - cluster-net
    ports:
      - 8081:8081
    depends_on:
      - "master-node"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role!=manager

# Uses cluster-net network
networks:
  cluster-net: