version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    deploy:
      mode: replicated # Required by Docker Swarm to make published ports work with other services
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    deploy:
      mode: global # Required by Docker Swarm to make published ports work with other services
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
